---
title: "Data Science Projects"
description: |
  A collection of some projects that may or may not be related to my research.
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: false
    css:
      - css/jmhardaw.css
      - css/strapless.css
twitter:
  creator: "@James_Hardaway"
base_url: https://www.nerdygi.com
preview: images/IMG-1633-sm.jpg
---

<!-- Remove margin under images -->
<style>
d-article img {
  margin-bottom: 0px;
}

.btn-primary {
    background-color: #74a08a;
    color: #FFFFFF;
    padding: 3px 5px 3px 5px;
    margin: 0 2px 0 2px;
    border-radius: 5px; /* Rounded edges */
    border: 0px;
}

.btn-primary:hover {
    background-color: #8a74a0;
    color: #FFFFFF;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(bs4cards)

# Read in projects csv file 
projects <- readr::read_csv(here::here("content", "projects.csv"))
```

```{r projects, echo=FALSE, layout="l-body-outset"}
projects %>% 
  bs4cards::cards(
    title = title,
    text = description,
    link = url,
    image = src,
    label_colour = "#ffffff",
    tags = paste("All;", tags),
    footer = tags,
    border_radius = 5
  )
```