---
title: "ECI 511 – Week 1 Review"
description: |
  Week 1 gave us an opportunity to meet the class and served as an introduction to the field of learning design and technology.
author:
  - name: James Hardaway
    url: https://scholar.google.com/citations?user=su16JUQAAAAJ&hl=en&authuser=1
date: 2021-07-04
categories:
  - ECI511
  - NC State
  - government
  - history
  - industry
  - military
  - portfolio
  - revolution
  - webpage
  - design
  - inquiry
  - leadership
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

For my intro to the Learning Design & Technology (LDT) program, I'm taking one 5-week summer class before going full time in the fall. ECI 511, Intro to LDT, is the recommended first course for the program and for good reason. The compressed schedule is designed to give a thorough, but quick, overview of the 3 core disciplines within the field of LDT: Leadership, Design, and Digital Inquiry. Here in week 1, we focused on how the LDT field has been established historically mainly driven by the technological revolution. The class material has a good mix of articles and videos to introduce us to how the field has evolved over the past 100 years. There is a major assignment each week and for this first week, my assignment was to establish this portfolio website. The intent is for me to use this portal to chart my progress through the program, displaying my work as well as what I'm learning by doing the work. The end state is to have a portfolio showing my progress in becoming a learning designer that could potentially be used as a launching point for my life after the program. Through this week's class material, my key insights are below:

-   Tech changes to education came from outside the school house (government, military, industry)

-   The speed of tech evolution (capability/capacity) is always under-valued/appreciated

-   Tech's ability to "revolutionize" learning has always been over-emphasized

-   Educational institutions are generally slow to adopt new technology/methods

-   Historically, tech's impact to learning has been on the margins (pencils/paper/blackboards becoming digitized), but we have yet to see a "revolution" in how we teach/learn.

For next week, we'll move into the Leadership domain of LDT and I get to produce my first "class." See you then!
